name: Auto-PR Feature
on:
  push:
    branches: [Feature/**/**]
    
jobs:
  pull-request:
    name: Open PR to develop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout
      
    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "develop"
        pr_title: "Pulling *'${{ github.ref }}'* into develop"
        pr_body: " :bangbang: *Automated Generate PR* with this runner :fast_forward: ${{ runner.name }}"
        pr_reviewer: "DevFauche,YoannBfauche"
        pr_assignee: "${{ github.actor }}"
        if : contains($(git rev-parse --short "$GITHUB_SHA"),'[startPR]')
        pr_draft: false 
        if : "!contains($(git rev-parse --short "$GITHUB_SHA"),'[startPR]')"
        prt_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
