name: Auto-PR Feature
on:
  push:
    branches: 
    - "Feature/**/**"
    - "BugFix/**/**"

jobs:
  pull-request:
    name: Open PR to develop
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: condition draft PR
      uses: haya14busa/action-cond@v1
      id: draftCondition
      with:
        cond: "contains(github.event.head_commit.message,'[startPR]')"
        if_true: false #draft is false 
        if_false: true # draft is true

    - name: create pull-request 
      if: "contains(github.event.head_commit.message,'[startPR]') || contains(github.event.head_commit.message,'[draftPR]')"
      uses: repo-sync/pull-request@v2 
      with:
        destination_branch: "develop"
        pr_title: "Pulling ${{ github.ref }} into develop"
        pr_body: " :bangbang: *Automated Generate PR* with this runner :fast_forward:"
        pr_reviewer: "DevFauche,YoannBfauche"
        pr_assignee: "${{ github.actor }}"
        pr_draft: ${{ steps.draftCondition.outputs.value }} # add draft mode or not, Cant pass a draft pr to open pr by ths strategy.
        github_token: ${{ secrets.GITHUB_TOKEN }}
